language: ruby
cache: bundler
before_install: gem install bundler -v 1.17.2
deploy:
  - provider: rubygems
    gem: doxie-scanner
    email: cristiano@betta.io
    on:
      tags: true
      rvm: 2.6.0
    api_key: $RUBYGEMS_API_KEY
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.6.0  # explicit branch used for deploying gem
  - ruby-head
  - jruby
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: 2.6.0